### ISSUE TITLE
Ability to query geospecies by ecological site ID

### ISSUE THREAD

**Issue by nstauffer** [Landscape-Data-Commons/main_api#12]
Currently, geoindicators is the only part of the API queryable by ecological site ID and it'd be helpful if at least geospecies was also. Mostly, this would be useful for applications like the benchmark histograms tool where folks may want to work with the species indicators on a per-ecosite basis. I don't know if it makes sense to be able to query the others (e.g. datalpi, gata gap) by ecosite, but if it's low-hanging fruit it'd probably be worth it.

**Comment by krstphrrr** [comment]
@nstauffer Ok! so because most of these tables should be queryable from a map, they have to be joined with header first (which houses the "EcologicalSiteId" field. This fact use to make ecological site id available in the result set of most queries, but not queryable by itself on any table. Latest update made dataHeader fields available to  be queried, so test them out and let me know if the results make sense! 

Also added the handling of an optional "limit" field if you want smaller sets to come back for debugging purposes. 
(usage example: https://api.landscapedatacommons.org/api/geoSpecies?EcologicalSiteId=R023XF082CA&limit=10 )

**Comment by nstauffer** [comment]
Cool beans! It looks like in order to handle geoSpecies I'll just need to convert from tall to wide format, but it's working like a charm. Thanks for looking into this and making the magic happen!
